### ISSUE TITLE
Question: Can we make detection area bigger?

### ISSUE THREAD

**Issue by masterofobzene** [freearhey/face-extractor#2]

**Comment by freearhey** [comment]
I have just added a new `--scale` argument through which you can control the size of the detection zone. For example:

```
python extract.py --input examples --scale 1.2
```

I hope this helps.

**Comment by masterofobzene** [comment]
> I have just added a new `--scale` argument through which you can control the size of the detection zone. For example:
> 
> ```
> python extract.py --input examples --scale 1.2
> ```
> 
> I hope this helps.

A little problem I see is that when the scale increases, the detection gets really worse. Is there any way to fix this?

**Comment by freearhey** [comment]
Could you provide any example?

**Comment by masterofobzene** [comment]
![imagen](https://user-images.githubusercontent.com/94469116/172745596-c993e191-5a2f-4f76-83b7-4310fdf79223.png)

using -s 1.6  (increasing this value makes it worse)
all have clear faces
images res +- 1000x800

![imagen](https://user-images.githubusercontent.com/94469116/172746523-ff47601e-075b-418b-a393-d36bf96d147e.png)

Value at 1.2:
![imagen](https://user-images.githubusercontent.com/94469116/172746648-6afb20de-f288-43f8-b068-97a7c4707b9a.png)

Value at 0.8:
![imagen](https://user-images.githubusercontent.com/94469116/172746808-6c81783b-60d4-429d-ab2f-38ba660bd1c2.png)

**Comment by freearhey** [comment]
Fixed in #4

**Comment by freearhey** [comment]
This is expected behavior since all found faces are now placed in the middle of the frame.

**Comment by freearhey** [comment]
Because, as far as I know, this is the only way to put the face in the center of the frame regardless of its position in the original photo.
